### ISSUE TITLE
Transfer Request @ RunIIFall15MiniAODv2 campaign (76X)

### ISSUE THREAD

**Issue by peruzzim** [CERN-PH-CMG/cmg-cmssw#618] opened 2016-02-12 16:14 UTC
Hi Yuta,

 could you please transfer these datasets?

/WWTo2L2Nu_13TeV-powheg/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
/DoubleEG/Run2015D-16Dec2015-v2/MINIAOD
/MuonEG/Run2015D-16Dec2015-v1/MINIAOD

Thanks,
 Marco

**Comment by gitytakahas** [comment] 2016-02-12 18:37
https://cmsweb.cern.ch/phedex/prod/Request::View?request=602341

Yuta

2016-02-12 17:14 GMT+01:00 peruzzim notifications@github.com:

> Hi Yuta,
> 
> could you please transfer these datasets?
> 
> /WWTo2L2Nu_13TeV-powheg/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
> /DoubleEG/Run2015D-16Dec2015-v2/MINIAOD
> /MuonEG/Run2015D-16Dec2015-v1/MINIAOD
> 
> Thanks,
> Marco
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CERN-PH-CMG/cmg-cmssw/issues/618.

## 

Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by peruzzim** [comment] 2016-02-18 10:02
Hi Yuta,

 could you please transfer this dataset?

/QCD_Pt-15to20_EMEnriched_TuneCUETP8M1_13TeV_pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM

Thanks, 
 Marco

**Comment by gitytakahas** [comment] 2016-02-18 10:14
https://cmsweb.cern.ch/phedex/prod/Request::View?request=607013

Y.

2016-02-18 11:02 GMT+01:00 peruzzim notifications@github.com:

> Hi Yuta,
> 
> could you please transfer this dataset?
> 
> /QCD_Pt-15to20_EMEnriched_TuneCUETP8M1_13TeV_pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
> 
> Thanks,
> Marco
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CERN-PH-CMG/cmg-cmssw/issues/618#issuecomment-185635468
> .

## 

Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by steggema** [comment] 2016-02-19 09:04
Hi Yuta,

Can you transfer this sample?

/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM

Thanks,
Jan

**Comment by gitytakahas** [comment] 2016-02-19 09:21
https://cmsweb.cern.ch/phedex/prod/Request::View?request=608662

Y.

2016-02-19 10:04 GMT+01:00 Jan Steggemann notifications@github.com:

> Hi Yuta,
> 
> Can you transfer this sample?
> 
> /WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
> 
> Thanks,
> Jan
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CERN-PH-CMG/cmg-cmssw/issues/618#issuecomment-186123049
> .

## 

Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by emanueledimarco** [comment] 2016-03-14 10:16
Hi Yuta, 

could you transfer these datasets at CERN:
/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
/WJetsToLNu_HT-600To800_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
/WZ_TuneCUETP8M1_13TeV-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM

Thanks a lot, 

```
                emanuele
```

**Comment by gitytakahas** [comment] 2016-03-14 10:21
https://cmsweb.cern.ch/phedex/prod/Request::View?request=626072

2016-03-14 11:16 GMT+01:00 Emanuele Di Marco notifications@github.com:

> Hi Yuta,
> 
> could you transfer these datasets at CERN:
> 
> /ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
> 
> /WJetsToLNu_HT-600To800_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
> 
> /WZ_TuneCUETP8M1_13TeV-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
> 
> Thanks a lot,
> 
> ```
>             emanuele
> ```
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CERN-PH-CMG/cmg-cmssw/issues/618#issuecomment-196240777
> .

## 

Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by mstoye** [comment] 2016-03-31 14:20
Hi Yuta,
Could you transfer
/WToTauNu_1J_8TeV-amcatnloFXFX-pythia8/Summer12DR53X-PU_S10_START53_V19-v1/AODSIM
/WToTauNu_2J_8TeV-amcatnloFXFX-pythia8/Summer12DR53X-PU_S10_START53_V19-v1/AODSIM/WToTauNu_0J_8TeV-amcatnloFXFX-pythia8/Summer12DR53X-PU_S10_START53_V19-v1/AODSIM
Regards and thanks,
Markus

**Comment by mdunser** [comment] 2016-03-31 14:35
Hi Markus,

currently our buffer is full (59.08 out of 60 TB). It's occupied by essentially two datasets that were transferred recently (in total 34 TB). Your datasets combine to 27.2 TB, so those won't fit at the moment I'm afraid.

I'll have to figure out if I can delete some of the huge datasets first before we can request yours.

I'll keep you updated,
-marc (the new yuta)

**Comment by mstoye** [comment] 2016-03-31 14:41
Hi Marc.
I will let you know once I am done with WToLNu_2J_8TeV-amcatnloFXFX-pythia8. It is running already. This should part of what is in the buffer.
Cheers,
Markus

**Comment by mdunser** [comment] 2016-04-05 14:10
Hi Markus, @mstoye 

after clearing some space, I was able to request 2 out of the three datasets you asked for (the 2j and 1j).
Once you tell me that you no longer need that one large sample, I can delete that one and request the last 0j chunk.

Here's the request for the 2 datasets: https://cmsweb.cern.ch/phedex/prod/Request::View?request=633080

-m

**Comment by leonoravesterbacka** [comment] 2016-04-07 08:08
Hi Yuta, 

Could you please transfer:
/ZNuNuGJets_MonoPhoton_PtG-130_TuneCUETP8M1_13TeV-madgraph/RunIIFall15MiniAODv1-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM

Thank you, 
Leonora

**Comment by mdunser** [comment] 2016-04-07 08:15
Hi Leonora,
request made: https://cmsweb.cern.ch/phedex/prod/Request::View?request=633675
-m

On 07 Apr 2016, at 10:08, Leonora Vesterbacka Olsson <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Yuta,

Could you please transfer:
/ZNuNuGJets_MonoPhoton_PtG-130_TuneCUETP8M1_13TeV-madgraph/RunIIFall15MiniAODv1-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM

Thank you,
Leonora

**Comment by leonoravesterbacka** [comment] 2016-04-11 07:27
Hi Marc, 

Could you please transfer these samples:
/QCD_HT100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
/QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
?

Thank you
Leonora

**Comment by mdunser** [comment] 2016-04-11 07:53
Hi Leonora,

here’s the request: https://cmsweb.cern.ch/phedex/prod/Request::View?request=635167

The first of the two samples is already at CERN.
-m

On 11 Apr 2016, at 09:27, Leonora Vesterbacka Olsson <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc,

Could you please transfer these samples:
/QCD_HT100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
/QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
?

Thank you
Leonora

**Comment by mstoye** [comment] 2016-04-11 20:59
Hi Marc,
Let me reiterate the request for:
/WToLNu_1J_8TeV-amcatnloFXFX-pythia8/Summer12DR53X-PU_S10_START53_V19-v1/AODSIM
/WToLNu_0J_8TeV-amcatnloFXFX-pythia8/Summer12DR53X-PU_S10_START53_V19-v1/AODSIM
/WToTauNu_0J_8TeV-amcatnloFXFX-pythia8/Summer12DR53X-PU_S10_START53_V19-v1/AODSIM
Cheers,
Markus

**Comment by mdunser** [comment] 2016-04-11 21:23
Hi Markus, @mstoye ,

sorry I don't recall noticing you made a request for the first two samples you mentioned (perhaps this was during the period of taking over from Yuta), apologies for that.

In any event, your sample requests sum up to 78.8 TB, whereas our total local buffer is 60 TB. Of those 60 TB, currently 58.8 TB are occupied so there's little leeway I'm afraid.

The problem is that even the WToTauNu sample you requested takes 11 TB of space which we can't accommodate as of now. However you said you might no longer need some of the large samples that you requested in the past, namely:

16.7 TB: /WToLNu_2J_8TeV-amcatnloFXFX-pythia8/Summer12DR53X-PU_S10_START53_V19-v1/AODSIM
10.0 TB: /WToTauNu_1J_8TeV-amcatnloFXFX-pythia8/Summer12DR53X-PU_S10_START53_V19-v1/AODSIM
5.4 TB: /WToTauNu_2J_8TeV-amcatnloFXFX-pythia8/Summer12DR53X-PU_S10_START53_V19-v1/AODSIM

If I could delete one of the two largest of these, it would free up enough space for the WToTauNu. But the other two samples take up more than 50% of our buffer _each_ so that will in any case be virtually impossible at the moment (or in general).

This being said, we are trying to perhaps do something about the size of the local buffer, but that will take time if it will happen at all (think weeks).

So to conclude: we can fit the WToTauNu_0J sample if perhaps you're done with one of the samples I listed. The other two won't fit easily but I'll talk to someone who might know what to do tomorrow and will let you know what comes out of it.

Best,
-m

**Comment by mstoye** [comment] 2016-04-11 22:01
Hi Marc,
I know the samples are large, I just wanted to remind that they are on the "waiting" list and need to be transferred. We can do this is bunches. I am currently updating the old CMSSW_5_3_X recipy for ntupels that unfortunately is out of date. Once the tupels are tested we can delete the three samples below you mentioned. It would be great if we than can transfer one of the samples listed here.
Cheers,
Markus

**Comment by mdunser** [comment] 2016-04-11 22:41
Hi Markus,

yes, you're surely on the waiting list. I had that WTauNu_0J sample in the back of my head, I was just waiting for your some clearance for that. After that I'll see what can be done with the two 30 TB ones.

I'll keep you posted,
-m

**Comment by mdunser** [comment] 2016-04-13 05:32
Hi Markus,

I just requested the last WToTauNu sample here: https://cmsweb.cern.ch/phedex/prod/Request::View?request=635786

Best,
-m

**Comment by bachtis** [comment] 2016-04-13 17:52
Hi Marc,
We need this sample for a tracking study we are doing:
/ZeroBias_0T/Run2015D-27Jan2016-v1/RECO

We need to get it to CERN then run on it once and then we delete it.
Can you do it?
M

**Comment by mdunser** [comment] 2016-04-13 18:15
Hi Michail,

here’s the request: https://cmsweb.cern.ch/phedex/prod/Request::View?request=635991
If you let me know once you’re done with it that would be much appreciated.

-m

On 13 Apr 2016, at 19:52, Michalis Bachtis <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc,
We need this sample for a tracking study we are doing:
/ZeroBias_0T/Run2015D-27Jan2016-v1/RECO

We need to get it to CERN then run on it once and then we delete it.
Can you do it?
M

**Comment by leonoravesterbacka** [comment] 2016-04-14 09:35
Hi Marc, 

could you please just transfer one last sample for me?

/GJets_HT-40To100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v3/MINIAODSIM

Thank you, 
Leonora

**Comment by mdunser** [comment] 2016-04-14 09:42
Hi Leonora,

here’s your last ever request: https://cmsweb.cern.ch/phedex/prod/Request::View?request=636200
Make the most of it.

Best,
-m

On 14 Apr 2016, at 11:35, Leonora Vesterbacka Olsson <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc,

could you please just transfer one last sample for me?

/GJets_HT-40To100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v3/MINIAODSIM

Thank you,
Leonora

**Comment by bachtis** [comment] 2016-04-19 13:22
Hi Marc,
Need this not for long:
 /JpsiToMuMu_JpsiPt8_TuneCUEP8M1_13TeV-pythia8/RunIIFall15DR76-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/AODSIM

The other one (RECO) didnt arrive yet -can we check why?

**Comment by mdunser** [comment] 2016-04-19 13:40
Hi Michalis,

request is here: https://cmsweb.cern.ch/phedex/prod/Request::View?request=638668
let me know once you no longer need it please.

the other sample is stuck at 99.3% since last week, no idea what’s happening. I’ll investigate
and come back to you once i know more.

-m

On 19 Apr 2016, at 15:22, Michalis Bachtis <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc,
Need this not for long:
/JpsiToMuMu_JpsiPt8_TuneCUEP8M1_13TeV-pythia8/RunIIFall15DR76-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/AODSIM

The other one (RECO) didnt arrive yet -can we check why?

**Comment by mdunser** [comment] 2016-04-19 16:16
Hi again,

the dataset from last week is still in transfer but the origin site (FNAL) seems to be experiencing
problems, so there is little to do other than wait. However the completion is 99.3% so you could
probably get the file list manually and run with that…

Otherwise we’ll need to wait.
-m

On 19 Apr 2016, at 15:32, Marc Dunser <marc.dunser@cern.ch<mailto:marc.dunser@cern.ch>> wrote:

Hi Michalis,

request is here: https://cmsweb.cern.ch/phedex/prod/Request::View?request=638668
let me know once you no longer need it please.

the other sample is stuck at 99.3% since last week, no idea what’s happening. I’ll investigate
and come back to you once i know more.

-m

On 19 Apr 2016, at 15:22, Michalis Bachtis <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc,
Need this not for long:
/JpsiToMuMu_JpsiPt8_TuneCUEP8M1_13TeV-pythia8/RunIIFall15DR76-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/AODSIM

The other one (RECO) didnt arrive yet -can we check why?

**Comment by leonoravesterbacka** [comment] 2016-04-26 12:23
Hi Marc,

I have one more transfer request if you don't mind. This time it is :

/QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM

Thank you

Leonora

2016-04-19 18:16 GMT+02:00 mdunser notifications@github.com:

> Hi again,
> 
> the dataset from last week is still in transfer but the origin site (FNAL)
> seems to be experiencing
> problems, so there is little to do other than wait. However the completion
> is 99.3% so you could
> probably get the file list manually and run with that…
> 
> Otherwise we’ll need to wait.
> -m
> 
> On 19 Apr 2016, at 15:32, Marc Dunser <marc.dunser@cern.ch<mailto:

**Comment by mdunser** [comment] 2016-04-26 14:44
Hi Leonora,

there is no way that this dataset will fit in the buffer anytime soon. We're above quota and the admins already made an exception for a large dataset.

There are two possibilities: we could free up some datasets that you had requested in the past or you run with useAAA, which should be alright for this dataset.

Let me know,
-m

**Comment by leonoravesterbacka** [comment] 2016-04-26 16:26
Hi Marc,

could you remove one of the other samples I asked for before? for example
/ZNuNuGJets_MonoPhoton_PtG-130_TuneCUETP8M1_13TeV-
madgraph/RunIIFall15MiniAODv1-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
or any of the other I asked for (in principle all samples I asked for), to
clear up some space, so that I we could transfer the
/QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-
PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM

Thank you,
Leonora

2016-04-26 16:44 GMT+02:00 mdunser notifications@github.com:

**Comment by mdunser** [comment] 2016-04-29 17:18
Hi Leonora,

request is made: https://cmsweb.cern.ch/phedex/prod/Request::View?request=643280

-m

**Comment by gitytakahas** [comment] 2016-05-03 13:11
Hi Marc,

Can you transfer following LHE files (needed for validation) ? 

/VBFHToTauTau_M125_13TeV_powheg_pythia8/RunIIWinter15wmLHE-MCRUN2_71_V1-v1/LHE
/GluGluHToTauTau_M125_13TeV_powheg_pythia8/RunIIWinter15wmLHE-MCRUN2_71_V1-v1/LHE

Thanks,
Yuta

**Comment by mdunser** [comment] 2016-05-03 13:18
Hi Yuta,

here’s the request: https://cmsweb.cern.ch/phedex/prod/Request::View?request=647533

-m

On 03 May 2016, at 15:11, Yuta Takahashi <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc,

Can you transfer following LHE files (needed for validation) ?

/VBFHToTauTau_M125_13TeV_powheg_pythia8/RunIIWinter15wmLHE-MCRUN2_71_V1-v1/LHE
/GluGluHToTauTau_M125_13TeV_powheg_pythia8/RunIIWinter15wmLHE-MCRUN2_71_V1-v1/LHE

Thanks,
Yuta

**Comment by cbotta** [comment] 2016-05-26 22:05
Hi Marc,

could you please transfer:
/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext1-v1/MINIAODSIM
/WJetsToLNu_HT-200To400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
/WJetsToLNu_HT-200To400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext1-v1/MINIAODSIM

thanks
cristina

**Comment by mdunser** [comment] 2016-05-27 05:46
ciao cristina,

at least two of these datasets are already at cern.
i made the request: https://cmsweb.cern.ch/phedex/prod/Request::View?request=671304
-m

On 27 May 2016, at 00:05, cbotta <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc,

could you please transfer:
/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext1-v1/MINIAODSIM
/WJetsToLNu_HT-200To400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
/WJetsToLNu_HT-200To400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext1-v1/MINIAODSIM

thanks
cristina

**Comment by cbotta** [comment] 2016-05-30 17:09
Hi Marc,

could you please transfer

/DYJetsToLL_M-5to50_HT-100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext1-v1/MINIAODSIM
/DYJetsToLL_M-5to50_HT-200to400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext1-v1/MINIAODSIM
/DYJetsToLL_M-5to50_HT-600toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext1-v1/MINIAODSIM

thanks
cristina

**Comment by mdunser** [comment] 2016-05-30 19:08
Hi Cristina,

the last of the samples should already be here.
The others are coming: https://cmsweb.cern.ch/phedex/prod/Request::View?request=677284
-m

On 30 May 2016, at 19:09, cbotta <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc,

could you please transfer

/DYJetsToLL_M-5to50_HT-100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext1-v1/MINIAODSIM
/DYJetsToLL_M-5to50_HT-200to400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext1-v1/MINIAODSIM
/DYJetsToLL_M-5to50_HT-600toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext1-v1/MINIAODSIM

thanks
cristina

**Comment by mverwe** [comment] 2016-06-08 11:02
Hi Marc,

These are the two RAW pp 5 TeV data sets we would like to have available for a short time on the T2 so that we can run a special reconstruction for jet energy uncertainties. We can delete them as soon as we finish the reconstruction (my guess is maximum 2 weeks but most likely shorter)
- /HighPtPhoton30AndZ/Run2015E-v1/RAW 2.5 TB
- /HighPtLowerJets/Run2015E-v1/RAW 5.8 TB

Thanks,

Marta

@dgulhan

**Comment by mdunser** [comment] 2016-06-08 11:17
Hi Marta,

request is made: https://cmsweb.cern.ch/phedex/prod/Request::View?request=692334

Might take a while, but I’ll keep an eye on it.

-marc

On 08 Jun 2016, at 13:02, Marta Verweij <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc,

These are the two RAW pp 5 TeV data sets we would like to have available for a short time on the T2 so that we can run a special reconstruction for jet energy uncertainties. We can delete them as soon as we finish the reconstruction (my guess is maximum 2 weeks but most likely shorter)
-   /HighPtPhoton30AndZ/Run2015E-v1/RAW 2.5 TB
-   /HighPtLowerJets/Run2015E-v1/RAW 5.8 TB

Thanks,

Marta

@dgulhanhttps://github.com/dgulhan

**Closed as completed** 2017-12-15 10:36 UTC
